### ISSUE TITLE
一加的链接

### ISSUE THREAD

**Issue by HanHanOuyeE** [rcmiku/Payload-Dumper-Compose#2]
一加手机，这个也是官方的包链接，用原本的py工具能解析，这个解析不行![Screenshot_2024-12-24-19-22-56-24_292ad96be42734c6301948080016640e.jpg](https://github.com/user-attachments/assets/b2ac6e80-7c4f-4d0d-bea3-ce3e9d6cb63e)

**Comment by rcmiku** [comment]
已修复
